spring:
    application:
        name: tai-orchestrator
    main:
        allow-circular-references: true
logging:
    level:
        root: INFO
        org:
            springframework: WARN
            hibernate: WARN
        # Global Tai domains
        tai:
            error: WARN
            conversation: DEBUG #INFO for less detailed history
            context: DEBUG
            decision: INFO
            performance: INFO
            trace: TRACE
tai:
    prompt:
        system-file: classpath:prompts/tai-system-prompt.txt
    logs:
        dir: ./tai-orchestrator/logs
#### Will be moved in dedicated modules ####
    ollama:
        base-url: http://localhost:11434
        chat-path: /api/chat
        model: tai-llama
        stream: false
        keep-alive: 30m
        connect-timeout-ms: 3000
        read-timeout-ms: 120000
    tts:
        piper:
            enabled: true
            executable: ./tai-tts/.venv/Scripts/piper.exe
            model: ./tai-tts/voices/en_GB-alba-medium.onnx
            config: ./tai-tts/voices/en_GB-alba-medium.onnx.json
            output-dir: ./tai-tts/output
            voice-id: en_GB-alba-medium
