#### Spring ####
spring.application.name=tai-orchestrator
spring.main.allow-circular-references=true

#### Mock ####
tai.mock.llm.delay-ms=4000
tai.mock.tts.playback-delay-ms=6000
tai.mock.tts.voice-id=slow-mock-voice

#### Ollama ####
tai.ollama.base-url=http://localhost:11434
tai.ollama.chat-path=/api/chat
tai.ollama.model=tai-llama
tai.ollama.stream=false
tai.ollama.keep-alive=30m
tai.ollama.connect-timeout-ms=3000
tai.ollama.read-timeout-ms=120000

#### Prompts ####
tai.prompt.system-file=classpath:prompts/tai-system-prompt.txt

### Logs ####
logging.config=classpath:logback-spring.xml
tai.logging.conversation-trace-enabled=true
tai.logging.log-llm-context=true
tai.logging.log-llm-context-full=false

#### TTS ####
tai.tts.piper.enabled=true
tai.tts.piper.segmentation-mode=single
tai.tts.piper.executable=./tai-tts/.venv/Scripts/piper.exe
tai.tts.piper.model=./tai-tts/voices/en_GB-alba-medium.onnx
tai.tts.piper.config=./tai-tts/voices/en_GB-alba-medium.onnx.json
tai.tts.piper.output-dir=./tai-tts/output
tai.tts.piper.voice-id=en_GB-alba-medium
# tai.tts.piper.sentence-silence=0.15
# tai.tts.piper.length-scale=1.0
# tai.tts.piper.noise-scale=0.667
# tai.tts.piper.noise-w-scale=0.8

#### STT ####
tai.stt.whisper.enabled=true
tai.stt.whisper.python-executable=./tai-stt/.venv/Scripts/python.exe
tai.stt.whisper.script-path=./tai-stt/scripts/transcribe_file.py
tai.stt.whisper.model-size=small
tai.stt.whisper.device=cpu
tai.stt.whisper.compute-type=int8

#### Audio capture ####
tai.audio.capture.output-dir=./tai-stt/input
tai.audio.capture.sample-rate=16000
tai.audio.capture.sample-size-bits=16
tai.audio.capture.channels=1
tai.audio.capture.signed=true
tai.audio.capture.big-endian=false
tai.audio.capture.buffer-size=4096
