// SPDX-License-Identifier: GPL-3.0-only
package com.toteuch.tai.events;

public enum EventType {
    LLM_RESPONSE_COMPLETED,
    LLM_RESPONSE_FAILED,
    TTS_PLAYBACK_STARTED,
    TTS_PLAYBACK_COMPLETED,
    TTS_PLAYBACK_FAILED,
    UI_MANUAL_TEXT_INPUT_RECEIVED,
    UI_TTS_TOGGLE_CHANGED,
    UI_OBSCENITY_FILTER_TOGGLE_CHANGED,
    UI_STOP_SPEAK_RECEIVED,
    STT_SPEECH_STARTED,
    STT_TRANSCRIPT_ACCEPTED,
    STT_TRANSCRIPT_UNINTELLIGIBLE,
    STT_TRANSCRIPT_NOISE,

    // Internal, mustn't be transiting outside the orchestrator
    ASSISTANT_REPLY_ACCEPTED,
    ASSISTANT_REPLY_FAILED,
    ASSISTANT_SPEECH_FAILED,
    ASSISTANT_SPEECH_STARTED,
    ASSISTANT_SPEECH_COMPLETED,
    ASSISTANT_STOP_SPEAK_RECEIVED,
    CLARIFICATION_REQUESTED,
    CONVERSATION_TURN_COMPLETED,
    USER_SPEECH_STARTED,
    USER_UTTERANCE_ACCEPTED
}
