package com.toteuch.tai.orchestrator.events;

import java.time.Instant;

/**
 * Base interface for all events flowing through the Tai orchestrator.
 *
 * <p>Events are the primary communication mechanism between external services
 * (STT, LLM, TTS, UI) and the orchestrator core, as well as within the orchestrator itself.</p>
 *
 * <p>Each event represents a fact that has already occurred and must be handled
 * by the system. Events must be immutable and fully describe what happened.</p>
 *
 * <p>Events are grouped into three main categories:
 * <ul>
 *     <li>Inbound events (from external services)</li>
 *     <li>Internal events (generated by the orchestrator)</li>
 *     <li>Control events (from UI or configuration changes)</li>
 * </ul>
 * </p>
 *
 * <p>The {@code correlationId} is used to track all events belonging to the same
 * conversation turn, enabling traceability across the full lifecycle:
 * user input → LLM → TTS → completion.</p>
 *
 * <p>Implementations should typically be Java {@code record}s for immutability and clarity.</p>
 */
public interface TaiEvent {

    /**
     * Unique identifier of the event.
     */
    String eventId();

    /**
     * Timestamp at which the event occurred.
     */
    Instant occurredAt();

    /**
     * Identifier used to correlate events belonging to the same logical operation
     * or conversation turn.
     */
    String correlationId();

    /**
     * Source of the event (STT, LLM, TTS, UI, or orchestrator).
     */
    EventSource source();

    /**
     * Type of the event.
     */
    EventType type();
}
