// SPDX-License-Identifier: GPL-3.0-only
package com.toteuch.tai.orchestrator.events.inbound.llm;

import com.toteuch.tai.orchestrator.events.EventSource;
import com.toteuch.tai.orchestrator.events.EventType;
import com.toteuch.tai.orchestrator.events.TaiEvent;
import java.time.Instant;

/**
 * Event emitted when the LLM service has completed the generation of a full reply.
 *
 * <p>This event closes the assistant thinking phase for a given conversation turn.
 * The response carried by this event is considered ready to be accepted, displayed,
 * and optionally sent to TTS.</p>
 *
 * @param responseText         the full generated reply text returned by the LLM
 * @param modelName            the name of the model that produced the response, if available
 * @param inputTokens          the number of input tokens used for the generation, if available
 * @param outputTokens         the number of output tokens generated by the model, if available
 * @param generationDurationMs the total generation duration in milliseconds, if available
 */
public record LlmResponseCompletedEvent(
        String eventId,
        Instant occurredAt,
        String correlationId,
        EventSource source,
        String responseText,
        String modelName,
        Integer inputTokens,
        Integer outputTokens,
        Long generationDurationMs)
        implements TaiEvent {
    @Override
    public EventType type() {
        return EventType.LLM_RESPONSE_COMPLETED;
    }
}
