package com.toteuch.tai.taiorchestrator.events;

public enum EventType {
    STT_FINAL_TRANSCRIPT_RECEIVED,
    LLM_RESPONSE_COMPLETED,
    LLM_RESPONSE_FAILED,
    TTS_PLAYBACK_STARTED,
    TTS_PLAYBACK_COMPLETED,
    TTS_PLAYBACK_FAILED,
    USER_UTTERANCE_ACCEPTED,
    LLM_GENERATION_REQUESTED,
    ASSISTANT_REPLY_ACCEPTED,
    TTS_PLAYBACK_REQUESTED,
    CONVERSATION_TURN_COMPLETED,
    CURRENT_SPEECH_INTERRUPTED,
    UI_MANUAL_TEXT_INPUT_RECEIVED,
    UI_TTS_TOGGLE_CHANGED,
    UI_OBSCENITY_FILTER_TOGGLE_CHANGED
}
